name: Demonstrate 360i Pipeline

on:
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.THREESIXTYEYE_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Create config.ini with token
        run: |
          echo "[RawDataSource]" >> ./config/config.ini
          echo "gh_token = $ACCESS_TOKEN" >> ./config/config.ini
          echo "gh_user_name=alidootson" >> ./config/config.ini
          echo "gh_repo_name=UpdatedCDISCPilotData" >> ./config/config.ini
          echo "gh_repo_path=UpdatedCDISCPilotData/CDASH/datasetjson/" >> ./config/config.ini

          echo "" >> ./config/config.ini
          echo "[Study]" >> ./config/config.ini
          echo "study_oid=360i-lzzt" >> ./config/config.ini

          echo "" >> ./config/config.ini
          echo "[Data]" >> ./config/config.ini
          echo "data_path=./data" >> ./config/config.ini

          echo "" >> ./config/config.ini
          echo "[SourceSystem]" >> ./config/config.ini
          echo "name=360i" >> ./config/config.ini
          echo "version=0.0.1" >> ./config/config.ini

          echo "" >> ./config/config.ini
          echo "[Commands]" >> ./config/config.ini
          echo "python=python3" >> ./config/config.ini

      - name: Print config.ini (token masked)
        run: |
          echo "Contents of config.ini:"
          cat ./config/config.ini
    
      - name: Run github2dsj.py and set output path
        id: github2dsj
        run: |
          OUTPUT=$(python github2dsj/github2dsj.py ie.json --path ./data)
          echo "dataset_path=$OUTPUT" >> $GITHUB_OUTPUT

      - name: Use dataset_path in dsjupversion.py
        run: |
          echo "Upversioning ${{ steps.github2dsj.outputs.dataset_path }}"
          python dsjupversion/dsjupversion.py -f "${{ steps.github2dsj.outputs.dataset_path }}"
